'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
// `selected` is one domain index or several (a product can switch on more than one; the bare chipset is all six).
export default function Silicon({selected=0,exploded=false,reduced=false}:{selected?:number|number[];exploded?:boolean;reduced?:boolean}){
const host=useRef<HTMLDivElement>(null),state=useRef({selected,exploded,reduced});state.current={selected,exploded,reduced};
useEffect(()=>{const el=host.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{el.style.background="url(./images/semiconductor-hero.png) center / cover";return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#131515',0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;el.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(7,8,9);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight('#e2e9ec','#352714',2.4));const light=new THREE.DirectionalLight('#ffcf92',4);light.position.set(3,7,4);scene.add(light);const back=new THREE.DirectionalLight('#afbdce',2);back.position.set(-4,2,-3);scene.add(back);
const group=new THREE.Group();scene.add(group);const mat=(color:string,metalness=.7,roughness=.35)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const dark=mat('#1d2021'),copper=mat('#b99062'),silver=mat('#888e8f');
function box(w:number,h:number,d:number,x:number,y:number,z:number,m:THREE.Material){const a=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);a.position.set(x,y,z);group.add(a);return a;}
const board=box(5,.18,5,0,-.25,0,mat('#23292a'));const substrate=box(4.2,.25,4.2,0,0,0,silver);box(3.9,.12,3.9,0,.18,0,dark);
const domains:THREE.Mesh[]=[];const traces=new THREE.BufferGeometry();const lines=[];
for(let i=0;i<6;i++){const x=(i%3-1)*1.13,z=(Math.floor(i/3)-.5)*1.7;const m=new THREE.MeshStandardMaterial({color:'#696354',metalness:.65,roughness:.35,emissive:'#b37537',emissiveIntensity:0});const d=box(1.04,.12,1.5,x,.32,z,m);domains.push(d);for(let row=0;row<7;row++)for(let col=0;col<5;col++){const cell=box(.15,.022,.15,x+(col-2)*.19,.394,z+(row-3)*.2,(col+row)%3===0?copper:silver);d.add(cell);cell.position.set((col-2)*.19,.08,(row-3)*.2);} }
for(let i=0;i<36;i++){let v=(i-17.5)*.13;box(.055,.04,.18,v,-.05,2.16,copper);box(.055,.04,.18,v,-.05,-2.16,copper);box(.18,.04,.055,2.16,-.05,v,copper);box(.18,.04,.055,-2.16,-.05,v,copper);lines.push(v,-.14,2.3,v,-.14,3.5+Math.abs(v)*.5,v,-.14,-2.3,v,-.14,-3.5-Math.abs(v)*.5);}
traces.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));const circuit=new THREE.LineSegments(traces,new THREE.LineBasicMaterial({color:'#ac7b46',transparent:true,opacity:.25}));group.add(circuit);
let frame=0,last=0,angle=0,drag=false,px=0;const down=(e:PointerEvent)=>{drag=true;px=e.clientX;el.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(drag){angle+=(e.clientX-px)*.008;px=e.clientX}};const up=()=>{drag=false};el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);
let lastWidth=0,lastHeight=0;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h||(w===lastWidth&&h===lastHeight))return;lastWidth=w;lastHeight=h;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};resize();const observer=new ResizeObserver(resize);observer.observe(el);const active={value:true};const visibility=new IntersectionObserver(([e])=>{active.value=e.isIntersecting});visibility.observe(el);
const tick=(t:number)=>{frame=requestAnimationFrame(tick);if(!active.value||document.hidden||t-last<32)return;last=t;const s=state.current;if(!s.reduced&&!drag)angle+=.0012;group.rotation.y=angle;group.rotation.z=s.reduced?0:Math.sin(t*.00025)*.018;domains.forEach((d,i)=>{d.position.y=THREE.MathUtils.lerp(d.position.y,s.exploded?.95+(i%3)*.12:.32,s.reduced?1:.12);(d.material as THREE.MeshStandardMaterial).emissiveIntensity=(Array.isArray(s.selected)?s.selected.includes(i):i===s.selected)?.95:0;});board.position.y=THREE.MathUtils.lerp(board.position.y,s.exploded?-1:-.25,s.reduced?1:.12);renderer.render(scene,camera)};tick(0);
return()=>{cancelAnimationFrame(frame);observer.disconnect();visibility.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});renderer.dispose();renderer.domElement.remove();};},[]);
return <div className="silicon-canvas" ref={host} role="img" aria-label="Interactive 3D conceptual DeepGrid silicon package showing six compute domains. Drag to rotate; use the labeled domain controls for details."/>;
}
